title: Mi Web
email: 2montenegroeduardo@gmail.com
description: Esta es una pagina creada para la venta y distribucion de productos de tecnologia 
baseurl: "/nanocompras"
url: "https://eduhigh.github.io"
author: Eduardo Montenegro
markdown: kramdown
theme: minima

collections:
  proyectos:
    output: true
